[package]
name = "bevy_hyda"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
lightningcss = "1.0.0-alpha.57"
quick-xml = { version = "0.35.0", features = ["serialize"] }
serde = "1.0.203"